<script src="{{ asset('v1/vendors/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('v1/vendors/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('v1/vendors/fastclick/lib/fastclick.js') }}"></script>
<script src="{{ asset('v1/vendors/nprogress/nprogress.js') }}"></script>
<script src="{{ asset('v1/vendors/Chart.js/dist/Chart.min.js') }}"></script>
<script src="{{ asset('v1/vendors/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('v1/vendors/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js') }}"></script>
<script src="{{ asset('v1/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<script src="{{ asset('v1/build/js/custom.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>